import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-tp',
  templateUrl: './tp.page.html',
  styleUrls: ['./tp.page.scss'],
})
export class TpPage implements OnInit {
public tp =[
  {title:"EiffelTower", description:"Eiffel Tower, French Tour Eiffel, Parisian landmark that is also a technological masterpiece in building-construction history. When the French government was organizing the International Exposition of 1889 to celebrate the centenary of the French Revolution, a competition was held for designs for a suitable monument. More than 100 plans were submitted, and the Centennial Committee accepted that of the noted bridge engineer Gustave Eiffel. Eiffels concept of a 300-metre (984-foot) tower built almost entirely of open-lattice wrought iron aroused amazement, skepticism, and no little opposition on aesthetic grounds. When completed, the tower served as the entrance gateway to the exposition.", image:"https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F28%2F2017%2F02%2Feiffel-tower-paris-france-EIFFEL0217.jpg&q=60"},
  {title:"Louvre", description:"The Louvre (English:the Louvre Museum), (French: Musée du Louvre), is the world's most-visited museum, and a historic landmark in Paris, France. It is the home of some of the best-known works of art, including the Mona Lisa and the Venus de Milo. A central landmark of the city, it is located on the Right Bank of the Seine in the city's 1st arrondissement (district or ward). At any given point in time, approximately 38,000 objects from prehistory to the 21st century are being exhibited over an area of 72,735 square meters (782,910 square feet).", image:"https://cdn-imgix.headout.com/mircobrands-content/image/4e9ebbf7ff686d29a41f4af39e8386ea-louvre%20museum.jpg"},
  {title:"London", description:"London is the capital and largest city of England and the United Kingdom with a total population of 9,002,488. It stands on the River Thames in south-east England at the head of a 50-mile (80 km) estuary down to the North Sea, and has been a major settlement for two millennia. The City of London, its ancient core and financial centre, was founded by the Romans as Londinium and retains boundaries close to its medieval ones. Since the 19th century, London has also referred to the metropolis around this core, historically split between the counties of Middlesex, Essex, Surrey, Kent, and Hertfordshire, which largely comprises Greater London, governed by the Greater London Authority. The City of Westminster, to the west of the City of London, has for centuries held the national government and parliament.", image:"https://www.visitbritain.com/sites/default/files/styles/consumer_vertical_hero__1920x1080/public/paragraphs_bundles/hero/london.jpg?itok=hBA3q24v"},
  {title:"Skógafoss", description:"Skógafoss is one of Iceland’s biggest and most beautiful waterfalls with an astounding width of 25 meters (82 feet) and a drop of 60 meters (197 feet). The waterfall is incorporated in plenty of self-drive tours and vacation packages around the country, like this 10-Day Road Trip and this 6-Day Winter Guided Tour. Almost all South Coast tours will visit Skogafoss. Those who rent a car can find this waterfall right by the Ring Road. Located on the Skógá river, this mighty cascade is clearly visible from Route 1 and is an excellent place to stop and stretch the legs while traveling Iceland’s South Coast. The river below Skógafoss holds a large char and salmon population and is thus a favorite spot for fishermen in the summer.Due to the amount of spray the cascade produces, at least one rainbow is present any time the sun emerges from behind the clouds. The land underneath the waterfall is very flat, allowing visitors to walk right up to the wall of water. This will get you drenched, although, on a warm summer day, it can be quite tempting. Skógafoss can also be viewed from the top as a steep staircase leads to an observational platform above the cascade. Many nesting seabirds can be found on the route up.", image:"https://res.cloudinary.com/itb-database/image/upload/s--wgdrTVeV--/c_fill,dpr_auto,f_auto,q_auto:eco,w_1280/v1/Places/lw6x02miu34wxdd7vwpj"},
  {title:"Great wall of China", description:"Great Wall of China, Chinese (Pinyin) Wanli Changcheng or (Wade-Giles romanization) Wan-li Ch’ang-ch’eng (“10,000-Li Long Wall”), extensive bulwark erected in ancient China, one of the largest building-construction projects ever undertaken. The Great Wall actually consists of numerous walls—many of them parallel to each other—built over some two millennia across northern China and southern Mongolia. The most extensive and best-preserved version of the wall dates from the Ming dynasty (1368–1644) and runs for some 5,500 miles (8,850 km) east to west from Mount Hu near Dandong, southeastern Liaoning province, to Jiayu Pass west of Jiuquan, northwestern Gansu province. This wall often traces the crestlines of hills and mountains as it snakes across the Chinese countryside, and about one-fourth of its length consists solely of natural barriers such as rivers and mountain ridges. Nearly all of the rest (about 70 percent of the total length) is actual constructed wall, with the small remaining stretches constituting ditches or moats. Although lengthy sections of the wall are now in ruins or have disappeared completely, it is still one of the more remarkable structures on Earth. The Great Wall was designated a UNESCO World Heritage site in 1987.", image:"https://cdn.mos.cms.futurecdn.net/5pCA2Sgpfj9Vu8XcALuMtb.jpg"}
];

  constructor() { }

  ngOnInit() {
  }

}
